#!/bin/bash
#
# generate the style file and its documentation
#
pdflatex sidenotes.ins
pdflatex sidenotes.dtx
makeindex -s gind.ist -o sidenotes.ind sidenotes.idx
makeindex -s gglo.ist -o sidenotes.gls sidenotes.glo
pdflatex sidenotes.dtx
#
# compile the example file
#
pdflatex caesar_example
biber caesar_example
pdflatex caesar_example
pdflatex caesar_example
pdflatex caesar_example
#
# clean up
#
rm sidenotes.glo sidenotes.gls sidenotes.ind sidenotes.idx 
rm sidenotes.ilg sidenotes.toc sidenotes.log sidenotes.aux
rm caesar_example.aux caesar_example.bbl caesar_example.bcf
rm caesar_example.bib caesar_example.blg caesar_example.log 
rm caesar_example.run.xml caesar_example.toc
#
# update the ctan directory to upload new files
#
cp README ../ctan
cp caesar_book.cls ../ctan
cp caesar_example.tex ../ctan
cp caesar_example.pdf ../ctan
cp sidenotes.dtx ../ctan
cp sidenotes.ins ../ctan
cp sidenotes.pdf ../ctan 
#
# update the files in the LaTeX search path
cp sidenotes.sty ~/Library/texmf/tex/latex/sidenotes.sty
cp caesar_book.cls ~/Library/texmf/tex/latex/caesar_book.cls
#
# update the targets directory
#
mv sidenotes.sty ../targets
mv sidenotes.pdf ../targets
mv caesar_example.pdf ../targets
