# This workflow will generate the dependent file automatically

name: dependencies

on:
  pull_request:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: check the pull request (branch) out
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: check if sidenote files changed
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            sidenotes:
              - 'latex/sources/sidenotes.dtx'
              - 'latex/sources/sidenotes.ins'

      - name: Set up LaTeX environment
        run: sudo apt-get update && sudo apt-get install -y texlive

      - name: Compile sidenotes
        if: steps.changes.outputs.sidenotes == 'true'
        working-directory: latex/sources
        run: |
          pdflatex -interaction=nonstopmode sidenotes.ins
          pdflatex -interaction=nonstopmode sidenotes.dtx
          makeindex -s gind.ist -o sidenotes.ind sidenotes.idx
          makeindex -s gglo.ist -o sidenotes.gls sidenotes.glo
          pdflatex -interaction=nonstopmode sidenotes.dtx
          rm sidenotes.glo sidenotes.gls sidenotes.ind sidenotes.idx
          rm sidenotes.ilg sidenotes.toc sidenotes.log sidenotes.aux
          mv sidenotes.sty ../targets
          cp sidenotes.pdf ../ctan
          mv sidenotes.pdf ../targets

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: dependend files generated
          title: Autogenerated files by pdflatex
          body: This is an auto-generated PR with dependend files.
          labels: automated pr
          branch: "dependencies/${{ github.head_ref }}"
          base: ${{ github.head_ref }}
