# This workflow will generate the dependent file automatically

name: dependencies

on:
  push:
    branches: [master]

jobs:
  LaTeX:
    runs-on: ubuntu-latest
    steps:
      - name: check the pull request (branch) out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: check if sidenote files changed
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            sidenotes:
              - 'latex/sources/sidenotes.dtx'
              - 'latex/sources/sidenotes.ins'
            example:
              - 'latex/sources/sidenotes.dtx'
              - 'latex/sources/sidenotes.ins'
              - 'latex/sources/caesar_example.tex'
              - 'latex/sources/caesar_book.cls'

      - name: Set up LaTeX environment
        if: steps.changes.outputs.sidenotes == 'true' || steps.changes.outputs.example == 'true'
        run: |
          sudo apt-get update && sudo apt-get install -y texlive-latex-extra biber

      - name: Compile sidenotes
        if: steps.changes.outputs.sidenotes == 'true'
        working-directory: latex/sources
        run: |
          pdflatex -interaction=nonstopmode sidenotes.ins
          pdflatex -interaction=nonstopmode sidenotes.dtx
          makeindex -s gind.ist -o sidenotes.ind sidenotes.idx
          makeindex -s gglo.ist -o sidenotes.gls sidenotes.glo
          pdflatex -interaction=nonstopmode sidenotes.dtx
          rm sidenotes.glo sidenotes.gls sidenotes.ind sidenotes.idx
          rm sidenotes.ilg sidenotes.toc sidenotes.log sidenotes.aux
          cp sidenotes.pdf ../ctan
          cp sidenotes.ins ../ctan
          cp sidenotes.dtx ../ctan

      - name: Compile example
        if: steps.changes.outputs.example == 'true'
        working-directory: latex/sources
        run: |
          pdflatex caesar_example
          biber caesar_example
          pdflatex caesar_example
          pdflatex caesar_example
          pdflatex caesar_example
          rm caesar_example.aux caesar_example.bbl caesar_example.bcf
          rm caesar_example.bib caesar_example.blg caesar_example.log
          rm caesar_example.run.xml caesar_example.toc
          cp caesar_example.tex ../ctan
          cp caesar_example.pdf ../ctan
          cp caesar_book.cls ../ctan
          mv caesar_example.pdf ../targets

      - name: Move sidenotes
        if: steps.changes.outputs.sidenotes == 'true'
        working-directory: latex/sources
        run: |
          mv sidenotes.pdf ../targets
          mv sidenotes.sty ../targets

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: target files generated
          title: Autogenerated files by pdflatex
          body: This is an auto-generated PR with dependencies.
          labels: automated pr
          branch: update-dependencies
