# This workflow will generate the files such as .sty from the sources

name: Generate-dependencies

on:
  push:
    branches-ignore:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: check the pull request (branch) out
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up LaTeX environment
        run: sudo apt-get update && sudo apt-get install -y texlive

      - name: Compile sidenotes
        working-directory: latex/sources
        run: |
          pdflatex -interaction=nonstopmode sidenotes.ins
          pdflatex -interaction=nonstopmode sidenotes.dtx
          makeindex -s gind.ist -o sidenotes.ind sidenotes.idx
          makeindex -s gglo.ist -o sidenotes.gls sidenotes.glo
          pdflatex -interaction=nonstopmode sidenotes.dtx
          rm sidenotes.glo sidenotes.gls sidenotes.ind sidenotes.idx
          rm sidenotes.ilg sidenotes.toc sidenotes.log sidenotes.aux

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: targets generated
          title: Autogenerated files by pdflatex
          body: This is an auto-generated PR with dependend files.
          labels: automated pr
          branch: pdflatex/${{ github.head_ref }}
          base: ${{ github.head_ref }}
