# This workflow will generate the sidenotes.sty and
# sidenotes.pdf from sidenotes.ins and sidenotes.dtx

name: sidenotes

on:
  push:
    branches-ignore:
      - master
    paths:
      - "latex/sources/sidenotes.ins"
      - "latex/sources/sidenotes.dtx"

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: check the pull request (branch) out
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up LaTeX environment
        run: sudo apt-get update && sudo apt-get install -y texlive

      - name: Compile sidenotes
        working-directory: latex/sources
        run: |
          pdflatex -interaction=nonstopmode sidenotes.ins
          pdflatex -interaction=nonstopmode sidenotes.dtx
          makeindex -s gind.ist -o sidenotes.ind sidenotes.idx
          makeindex -s gglo.ist -o sidenotes.gls sidenotes.glo
          pdflatex -interaction=nonstopmode sidenotes.dtx
          rm sidenotes.glo sidenotes.gls sidenotes.ind sidenotes.idx
          rm sidenotes.ilg sidenotes.toc sidenotes.log sidenotes.aux

      - name: Copy/move the files
        working-directory: latex/sources
        run: |
          mv sidenotes.sty ../targets
          cp sidenotes.pdf ../ctan
          mv sidenotes.pdf ../targets

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: sidenotes.sty and .pdf generated
          title: Autogenerated files (sidenotes) by pdflatex
          body: This is an auto-generated PR with dependend files (sidenotes).
          labels: automated pr
          branch: "sidenotes/${{ github.ref }}"
